### ISSUE TITLE
Update to 1.19.3

### ISSUE THREAD

**Issue by connorslade** [connorslade/SigmaUtils#9]
i had no idea this would be so much work,,,

## New Module Ideas
 - [x] Get No Chat Reports module working again! [Important]
 - [x] Update No Telemetry module with [this](https://github.com/Aizistral-Studios/No-Chat-Reports/blob/1.19.3-Unified/src/main/java/com/aizistral/nochatreports/common/mixins/client/MixinYggdrasilUserApiService.java) also [this](https://github.com/Aizistral-Studios/No-Chat-Reports/blob/1.19.3-Unified/src/main/java/com/aizistral/nochatreports/common/mixins/client/MixinMinecraft.java#L40).

## Changes
- Removed Private Message Notifier
- Removed Force Fly (was unfinished)

## TODO
- [x] Fix crash on Sound Control
- [x] Fix Confirm Disconnect (broken mixin GameMenuScreenMixin)
- [x] Fix Ui Tweaks audioMuteButton
- [x] Fix NoTelemetry (TelemetryManager)
- [x] Do a new Packet Dump
